# Generated by Django 2.0.6 on 2018-06-22 15:20

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('finished', 'Finished')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Carteras Activas',
                'verbose_name': 'Cartera Activa',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_csv', models.FileField(help_text='El archivo debe tener dos columnas: DNI;Sueldo', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sueldos',
                'verbose_name': 'Sueldo',
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dump', models.FileField(blank=True, null=True, upload_to='')),
                ('generate', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('downloading', 'Downloading'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Snapshots',
                'verbose_name': 'Snapshot',
            },
        ),
        migrations.CreateModel(
            name='SnapshotRestore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_name', models.CharField(default=core.models.generate_dbname, editable=False, max_length=50)),
                ('database_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Snapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Snapshots Restore',
                'verbose_name': 'Snapshot Restore',
            },
        ),
        migrations.AddField(
            model_name='activewallet',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Salary'),
        ),
        migrations.AddField(
            model_name='activewallet',
            name='snapshot_restore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SnapshotRestore'),
        ),
        migrations.AddField(
            model_name='activewallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
