# Generated by Django 2.0.6 on 2018-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cadeterightssupport_cashiorightssupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activewallet',
            options={'permissions': (('active_wallet_access', 'Can access active wallet'),), 'verbose_name': 'Cartera Activa', 'verbose_name_plural': 'Carteras Activas'},
        ),
        migrations.AlterField(
            model_name='activewallet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('finished', 'Terminado')], default='pending', max_length=20),
        ),
    ]
