# Generated by Django 2.0.6 on 2018-07-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_focusgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activewallet',
            options={'permissions': (('active_wallet_access', 'Can access active wallet'),), 'verbose_name': 'Cartera Activa', 'verbose_name_plural': '5. Carteras Activas'},
        ),
        migrations.AlterModelOptions(
            name='focusgroup',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': '2. Grupos'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Sueldo', 'verbose_name_plural': '1. Sueldos'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'verbose_name': 'Snapshot', 'verbose_name_plural': '3. Snapshots'},
        ),
        migrations.AlterModelOptions(
            name='snapshotrestore',
            options={'verbose_name': 'Snapshot Restore', 'verbose_name_plural': '4. Snapshots Restore'},
        ),
        migrations.AddField(
            model_name='activewallet',
            name='focusgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FocusGroup'),
        ),
    ]
