# Generated by Django 2.0.6 on 2018-08-02 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20180718_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveWalletProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('mambu_generating', 'Generando Snapshot'), ('downloading', 'Descargando Snapshot'), ('restoring', 'Restaurando Snapshot'), ('wallet_generating', 'Generando Cartera'), ('finished', 'Terminado')], default='pending', max_length=20)),
                ('active_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ActiveWallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('active_wallet_access', 'Can access active wallet'),),
                'verbose_name_plural': '6. Procesos de Carteras Activas',
                'verbose_name': 'Proceso de Cartera Activa',
            },
        ),
    ]
