# Generated by Django 2.0.6 on 2018-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180718_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddlewareRightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('middleware_access', 'Can access Middleware'),),
                'managed': False,
            },
        ),
    ]
