# Generated by Django 2.0.6 on 2018-08-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activewalletprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activewallet',
            name='focusgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FocusGroup'),
        ),
        migrations.AlterField(
            model_name='activewalletprocess',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente 1/6'), ('mambu_generating', 'Generando Snapshot 2/6'), ('downloading', 'Descargando Snapshot 3/6'), ('restoring', 'Restaurando Snapshot 4/6'), ('wallet_generating', 'Generando Cartera 5/6'), ('finished', 'Terminado')], default='pending', max_length=20),
        ),
    ]
