# Generated by Django 2.0.6 on 2018-08-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180813_1300'),
        ('core', '0006_middlewarerightssupport'),
    ]

    operations = [
    ]
