# Generated by Django 2.0.6 on 2018-08-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20180816_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('admin_access', 'Can access Administration'),),
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cashiorightssupport',
            options={'managed': False, 'permissions': (('cashio_access', 'Can access CashIO'), ('bank_access', 'Can access Bank Config'))},
        ),
    ]
