# Generated by Django 2.0.6 on 2018-08-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_collectioncycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncycle',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='collectioncycle',
            name='middle_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='collectioncycle',
            name='start_date',
            field=models.DateField(),
        ),
    ]
