# Generated by Django 2.0.6 on 2018-08-24 14:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180821_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activewallet',
            options={'permissions': (('active_wallet_access', 'Can access active wallet'),), 'verbose_name': 'Cartera Activa', 'verbose_name_plural': '6. Carteras Activas'},
        ),
        migrations.AlterModelOptions(
            name='activewalletprocess',
            options={'permissions': (('active_wallet_access', 'Can access active wallet'),), 'verbose_name': 'Proceso de Cartera Activa', 'verbose_name_plural': '7. Procesos de Carteras Activas'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'verbose_name': 'Snapshot', 'verbose_name_plural': '4. Snapshots'},
        ),
        migrations.AlterModelOptions(
            name='snapshotrestore',
            options={'verbose_name': 'Snapshot Restore', 'verbose_name_plural': '5. Snapshots Restore'},
        ),
        migrations.AddField(
            model_name='collectioncycle',
            name='result',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path),
        ),
        migrations.AlterField(
            model_name='collectioncycle',
            name='end_date',
            field=models.DateField(help_text='Indica el fin del ciclo de cobranza (exclusiva, debe coincidir con la fecha de inicio del mes siguiente)', verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='collectioncycle',
            name='middle_date',
            field=models.DateField(help_text='Indica el comienzo de la segunda quincena (inclusiva)', verbose_name='Fecha Inicio 2da quincena'),
        ),
        migrations.AlterField(
            model_name='collectioncycle',
            name='start_date',
            field=models.DateField(help_text='Indica el inicio del ciclo de cobranza (inclusiva)', verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='focusgroup',
            name='focusgroup_csv',
            field=models.FileField(help_text="El archivo debe tener dos columnas separadas por 'coma': DNI,Grupo", upload_to=''),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_csv',
            field=models.FileField(help_text="El archivo debe tener dos columnas separadas por 'punto-y-coma': DNI;Sueldo", upload_to=''),
        ),
    ]
