# Generated by Django 2.0.6 on 2018-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180824_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncycle',
            name='end_date',
            field=models.DateField(help_text='Indica el fin del ciclo de cobranza (exclusiva, debe coincidir con la fecha de inicio del mes siguiente)', unique=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='collectioncycle',
            name='start_date',
            field=models.DateField(help_text='Indica el inicio del ciclo de cobranza (inclusiva)', unique=True, verbose_name='Fecha Inicio'),
        ),
    ]
