# Generated by Django 2.0.6 on 2018-08-31 14:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180824_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiorightssupport',
            options={'managed': False, 'permissions': (('cashio_access', 'Can access CashIO'), ('bank_access', 'Can access Bank Config'), ('active_wallet_access', 'Can access Carteras Activas'), ('active_wallet_add', 'Can add Carteras Activas'), ('strategy_access', 'Can access Estrategias'), ('strategy_exec_access', 'Can access Ejecuciones'), ('strategy_exec_add', 'Can add Ejecuciones'))},
        ),
        migrations.AlterField(
            model_name='collectioncycle',
            name='result',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera Inicial'),
        ),
    ]
