# Generated by Django 2.0.6 on 2018-08-31 16:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180831_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='activewallet',
            name='resultCollection',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path),
        ),
    ]
