# Generated by Django 2.0.6 on 2018-08-31 16:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_activewallet_resultcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activewallet',
            name='result',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera Barrido'),
        ),
        migrations.AlterField(
            model_name='activewallet',
            name='resultCollection',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera Cobranzas'),
        ),
    ]
