# Generated by Django 2.0.6 on 2018-09-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180904_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='activewalletprocess',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activewalletprocess',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente 1/6'), ('mambu_generating', 'Generando Snapshot 2/6'), ('downloading', 'Descargando Snapshot 3/6'), ('restoring', 'Restaurando Snapshot 4/6'), ('wallet_generating', 'Generando Cartera 5/6'), ('finished', 'Terminado'), ('failure', 'Fallido')], default='pending', max_length=20),
        ),
    ]
