# Generated by Django 2.0.6 on 2018-09-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180906_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activewallet',
            name='snapshot_restore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SnapshotRestore'),
        ),
    ]
