# Generated by Django 2.0.6 on 2018-09-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180913_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiorightssupport',
            options={'managed': False, 'permissions': (('cashio_access', 'Can access CashIO'), ('bank_access', 'Can access Bank Config'), ('active_wallet_access', 'Can access Carteras Activas'), ('active_wallet_add', 'Can add Carteras Activas'), ('strategy_access', 'Can access Estrategias'), ('strategy_exec_access', 'Can access Ejecuciones'), ('strategy_exec_add', 'Can add Ejecuciones'), ('active_wallet_download', 'Can download Cartera Activa'), ('active_wallet_download_collection', 'Can download Cartera Activa Cobranzas'), ('agent_data_access', 'Can access Datos Agentes Pago'), ('paying_stg_access', 'Can access Estrategias Bancos'))},
        ),
    ]
