# Generated by Django 2.0.6 on 2018-10-03 16:36

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_auto_20180919_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericCashin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashin_csv', models.FileField(editable=False, upload_to=core.models.upload_path, verbose_name='Cashin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('finished', 'Terminado')], default='pending', editable=False, max_length=20)),
                ('resume', models.TextField(editable=False)),
                ('approved_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashin Generico',
                'verbose_name_plural': '8. Cashin Genericos',
            },
        ),
        migrations.AlterModelOptions(
            name='middlewarerightssupport',
            options={'managed': False, 'permissions': (('middleware_access', 'Can access Middleware'), ('cashin_process_access', 'Can access Cashin Process Status'), ('cashout_summaries_access', 'Can access Cashout Summaries'), ('mw_companies_access', 'Can access Companies'))},
        ),
    ]
