# Generated by Django 2.0.6 on 2018-10-03 16:47

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181003_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcashin',
            name='approved_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genericcashin',
            name='cashin_csv',
            field=models.FileField(help_text='Archivo CSV: Fecha_Cobro;Nro_Operacion;Nombre del titular de la cuenta;DNI;Id_Transaccion_Banco;Importe;Estado;CBU;Banco', upload_to=core.models.upload_path, verbose_name='Cashin'),
        ),
    ]
