# Generated by Django 2.0.6 on 2018-10-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20181003_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcashin',
            name='comment',
            field=models.CharField(max_length=500, null=True, verbose_name='Motivo'),
        ),
    ]
