# Generated by Django 2.0.6 on 2018-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_genericcashin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcashin',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='genericcashin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pending_approve', 'Pendiente Aprobación'), ('approved', 'Aprobado'), ('error', 'Error'), ('finished', 'Enviado')], default='pending', editable=False, max_length=20),
        ),
    ]
