# Generated by Django 2.0.6 on 2018-10-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20181005_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcashin',
            name='cashin_username',
            field=models.CharField(choices=[('mambu-welp-ar', 'mambu-welp-ar')], default='mambu-welp-ar', editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='genericcashin',
            name='approved_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
