# Generated by Django 2.0.6 on 2018-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181005_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcashin',
            name='bank',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
