# Generated by Django 2.0.6 on 2018-10-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_genericcashin_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericcashin',
            old_name='cashin_username',
            new_name='consumer_username',
        ),
    ]
