# Generated by Django 2.0.6 on 2018-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20181005_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcashin',
            name='error_detail',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
