# Generated by Django 2.0.6 on 2018-10-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_genericcashin_error_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrightssupport',
            options={'managed': False, 'permissions': (('admin_access', 'Can access Administration'), ('cashin_process_approve', 'Can approve Cashin Generico'))},
        ),
    ]
