# Generated by Django 2.0.6 on 2018-10-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20181008_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadeterightssupport',
            options={'managed': False, 'permissions': (('cadete_access', 'Can access Cadete'), ('cadete_configuration_edit', 'Can edit Configuraciones'), ('cadete_operations_edit', 'Can edit Operaciones'))},
        ),
    ]
