# Generated by Django 2.0.6 on 2018-10-30 20:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20181018_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='middlewarerightssupport',
            options={'managed': False, 'permissions': (('middleware_access', 'Can access Middleware'), ('cashin_process_access', 'Can access Cashin Process Status'), ('cashout_summaries_access', 'Can access Cashout Summaries'), ('cashout_summaries_car_access', 'Can access Cashout Summaries of Creditos Al Rio'), ('cashout_summaries_welp_access', 'Can access Cashout Summaries of Wenance'), ('mw_companies_access', 'Can access Companies'))},
        ),
        migrations.AlterField(
            model_name='genericcashin',
            name='cashin_csv',
            field=models.FileField(help_text='Archivo CSV: Fecha_Cobro,Nro_Operacion,Nombre del titular de la cuenta,DNI,Id_Transaccion_Banco,Importe,Estado,CBU,Banco', upload_to=core.models.upload_path, verbose_name='Cashin'),
        ),
    ]
