# Generated by Django 2.0.6 on 2018-11-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20181030_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='middlewarerightssupport',
            options={'managed': False, 'permissions': (('middleware_access', 'Can access Middleware'), ('cashin_process_access', 'Can access Cashin Process Status'), ('cashout_summaries_access', 'Can access Cashout Summaries'), ('cashout_summaries_car_access', 'Can access Cashout Summaries of Creditos Al Rio'), ('cashout_summaries_welp_access', 'Can access Cashout Summaries of Wenance'), ('mw_companies_access', 'Can access Companies'), ('cashin_binnacle_summaries_access', 'Can access Cashin Bitacora'))},
        ),
    ]
