# Generated by Django 2.0.6 on 2018-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20181101_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccessRightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('company_wenance', 'Belongs to wenance'), ('company_car', 'Belongs to Créditos Al Río')),
                'managed': False,
            },
        ),
    ]
