# Generated by Django 2.0.6 on 2018-11-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_companyaccessrightssupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='middlewarerightssupport',
            options={'managed': False, 'permissions': (('middleware_access', 'Can access Middleware'), ('cashin_process_access', 'Can access Cashin Process Status'), ('cashout_summaries_access', 'Can access Cashout Summaries'), ('mw_companies_access', 'Can access Companies'), ('cashin_binnacle_summaries_access', 'Can access Cashin Bitacora'))},
        ),
    ]
