# Generated by Django 2.0.6 on 2018-12-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20181107_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondiRightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('bondi_access', 'Can access Bondi'), ('bondi_topics_edit', 'Can edit Topics')),
                'managed': False,
            },
        ),
    ]
