# Generated by Django 2.0.6 on 2019-01-14 15:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_bondirightssupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiorightssupport',
            options={'managed': False, 'permissions': (('cashio_access', 'Can access CashIO'), ('bank_access', 'Can access Bank Config'), ('active_wallet_access', 'Can access Carteras Activas'), ('active_wallet_add_access', 'Can add Carteras Activas'), ('buckets_strategy_access_debito_directo', 'Can access [debito_directo] Estrategias de Buckets'), ('buckets_strategy_access_renos', 'Can access [renos] Estrategias de Buckets'), ('buckets_strategy_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Estrategias de Buckets'), ('strategy_exec_access_debito_directo', 'Can access [debito_directo] Ejecuciones'), ('strategy_exec_access_renos', 'Can access [renos] Ejecuciones'), ('strategy_exec_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Ejecuciones'), ('strategy_exec_add_access_debito_directo', 'Can add [debito_directo] Ejecuciones'), ('strategy_exec_add_access_renos', 'Can add [renos] Ejecuciones'), ('strategy_exec_add_access_cobranza_atencion_cliente', 'Can add [cobranza_atencion_cliente] Ejecuciones'), ('active_wallet_download_access', 'Can download Cartera Activa'), ('active_wallet_download_collection_access', 'Can download Cartera Activa Cobranzas'), ('active_wallet_download_reno_access', 'Can download Cartera de Renos'), ('agent_data_access', 'Can access Datos Agentes Pago'), ('outputs_strategies_access_debito_directo', 'Can access [debito_directo] Outputs Strategies'), ('outputs_strategies_access_renos', 'Can access [renos] Outputs Strategies'), ('outputs_strategies_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Outputs Strategies'), ('paying_agents_strategy_access', 'Can access Estrategias Bancos'), ('data_source_reader_settings_access_debito_directo', 'Can access [debito_directo] Data Source Reader Settings'), ('data_source_reader_settings_access_renos', 'Can access [renos] Data Source Reader Settings'), ('data_source_reader_settings_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Data Source Reader Settings'))},
        ),
        migrations.AddField(
            model_name='activewallet',
            name='resultReno',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera de Renos'),
        ),
        migrations.AlterField(
            model_name='activewallet',
            name='result',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera de Debito Directo'),
        ),
        migrations.AlterField(
            model_name='activewallet',
            name='resultCollection',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera de Cobranzas a Clientes'),
        ),
    ]
