# Generated by Django 2.0.6 on 2019-01-28 17:33

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0036_auto_20190114_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveWalletReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera de Debito Directo')),
                ('resultCollection', models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera de Cobranzas a Clientes')),
                ('resultReno', models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera de Renos')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('finished', 'Terminado')], default='pending', max_length=20)),
                ('focusgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FocusGroup')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Salary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartera Activa',
                'verbose_name_plural': '8. Carteras Activas x Reporte',
                'permissions': (('active_wallet_access', 'Can access active wallet'),),
            },
        ),
        migrations.AlterModelOptions(
            name='genericcashin',
            options={'verbose_name': 'Cashin Generico', 'verbose_name_plural': '9. Cashin Genericos'},
        ),
    ]
