# Generated by Django 2.0.6 on 2019-01-28 19:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190128_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='activewalletreport',
            name='origin_report',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Reporte con datos origen'),
        ),
    ]
