# Generated by Django 2.0.6 on 2019-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_activewalletreport_origin_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncycle',
            name='start_process_date',
            field=models.DateField(help_text="Indica el inicio del proceso (fecha de la 'foto')", null=True, unique=True, verbose_name='Fecha Inicio de Proceso'),
        ),
        migrations.AlterField(
            model_name='activewalletreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('processing', 'Procesando'), ('finished', 'Terminado')], default='pending', max_length=20),
        ),
    ]
