# Generated by Django 2.0.6 on 2019-04-12 14:10

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20190207_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiorightssupport',
            options={'managed': False, 'permissions': (('cashio_access', 'Can access CashIO'), ('bank_access', 'Can access Bank Config'), ('active_wallet_access', 'Can access Carteras Activas'), ('active_wallet_add_access', 'Can add Carteras Activas'), ('buckets_strategy_access_debito_directo', 'Can access [debito_directo] Estrategias de Buckets'), ('buckets_strategy_access_reno', 'Can access [reno] Estrategias de Buckets'), ('buckets_strategy_access_cobranza_espana', 'Can access [espana] Estrategias de Buckets'), ('buckets_strategy_access_cobranza_mexico', 'Can access [mexico] Estrategias de Buckets'), ('buckets_strategy_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Estrategias de Buckets'), ('strategy_exec_access_debito_directo', 'Can access [debito_directo] Ejecuciones'), ('strategy_exec_access_reno', 'Can access [reno] Ejecuciones'), ('strategy_exec_access_cobranza_espana', 'Can access [espana] Ejecuciones'), ('strategy_exec_access_cobranza_mexico', 'Can access [mexico] Ejecuciones'), ('strategy_exec_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Ejecuciones'), ('strategy_exec_add_access_debito_directo', 'Can add [debito_directo] Ejecuciones'), ('strategy_exec_add_access_reno', 'Can add [reno] Ejecuciones'), ('strategy_exec_add_access_cobranza_espana', 'Can add [espana] Ejecuciones'), ('strategy_exec_add_access_cobranza_mexico', 'Can add [mexico] Ejecuciones'), ('strategy_exec_add_access_cobranza_atencion_cliente', 'Can add [cobranza_atencion_cliente] Ejecuciones'), ('active_wallet_download_access', 'Can download Cartera Activa Debito Directo'), ('active_wallet_download_collection_access', 'Can download Cartera Activa Cobranzas'), ('active_wallet_download_access_cobranza_espana', 'Can download Cartera de España'), ('active_wallet_download_access_cobranza_mexico', 'Can download Cartera de México'), ('active_wallet_download_access_reno', 'Can download Cartera de Renos'), ('agent_data_access', 'Can access Datos Agentes Pago'), ('outputs_strategy_access_debito_directo', 'Can access [debito_directo] Outputs Strategies'), ('outputs_strategy_access_reno', 'Can access [reno] Outputs Strategies'), ('outputs_strategy_access_cobranza_espana', 'Can access [espana] Outputs Strategies'), ('outputs_strategy_access_cobranza_mexico', 'Can access [mexico] Outputs Strategies'), ('outputs_strategy_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Outputs Strategies'), ('paying_agents_strategy_access_debito_directo', 'Can access [debito_directo] Estrategias Bancos'), ('paying_agents_strategy_access_reno', 'Can access [reno] Estrategias Bancos'), ('paying_agents_strategy_access_cobranza_espana', 'Can access [cobranza_espana] Estrategias Bancos'), ('paying_agents_strategy_access_cobranza_mexico', 'Can access [mexico] Estrategias Bancos'), ('paying_agents_strategy_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Estrategias Bancos'), ('data_source_reader_settings_access_debito_directo', 'Can access [debito_directo] Data Source Reader Settings'), ('data_source_reader_settings_access_reno', 'Can access [reno] Data Source Reader Settings'), ('data_source_reader_settings_access_cobranza_espana', 'Can access [cobranza_espana] Data Source Reader Settings'), ('data_source_reader_settings_access_cobranza_mexico', 'Can access [cobranza_mexico] Data Source Reader Settings'), ('data_source_reader_settings_access_cobranza_atencion_cliente', 'Can access [cobranza_atencion_cliente] Data Source Reader Settings'))},
        ),
        migrations.AddField(
            model_name='activewallet',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activewallet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('finished', 'Terminado'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='activewalletreport',
            name='origin_report',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Reporte con datos origen'),
        ),
    ]
