# Generated by Django 2.0.6 on 2019-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20190412_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='activewalletreport',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activewalletreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('processing', 'Procesando'), ('finished', 'Terminado'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
