# Generated by Django 2.0.6 on 2019-10-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190415_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcashin',
            name='consumer_username',
            field=models.CharField(choices=[(None, 'Seleccione...'), ('mambu-welp-ar', 'mambu-welp-ar'), ('mambu-creditoalrio-ar', 'mambu-creditoalrio-ar'), ('mambu-welp-es', 'mambu-welp-es')], default=None, max_length=50, null=True),
        ),
    ]
