# Generated by Django 2.0.6 on 2019-10-30 18:27

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_auto_20191023_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCashin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(choices=[('mambu-welp-ar', 'mambu-welp-ar'), ('mambu-creditoalrio-ar', 'mambu-creditoalrio-ar'), ('mambu-welp-es', 'mambu-welp-es')], default=None, max_length=50, null=True)),
                ('cashin_file', models.FileField(upload_to=core.models.upload_path, verbose_name='Cashin')),
                ('channel', models.CharField(choices=[('xxx', 'XXXX'), ('yyy', 'YYY'), ('zzz', 'ZZZ')], default=None, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashin Manual',
                'verbose_name_plural': 'Cashins Manual',
                'permissions': (('manual_cashin_access', 'Can access Manual Cashin'), ('manual_cashin_create', 'Can create Manual Cashin')),
            },
        ),
    ]
