# Generated by Django 2.0.6 on 2019-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_manualcashin'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcashin',
            name='channel_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manualcashin',
            name='channel',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manualcashin',
            name='tenant',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
