# Generated by Django 2.0.6 on 2019-11-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20191104_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualcashin',
            old_name='channel_type',
            new_name='agreement_type',
        ),
        migrations.AddField(
            model_name='manualcashin',
            name='agreement',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
