# Generated by Django 2.0.6 on 2019-12-18 16:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20191128_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='activewallet',
            name='resultFeesCharged',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cuotas cobradas'),
        ),
        migrations.AddField(
            model_name='activewalletreport',
            name='resultFeesCharged',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera Cuotas Cobradas'),
        ),
    ]
