# Generated by Django 2.0.6 on 2020-01-13 19:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20191218_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='activewallet',
            name='resultMifosCa',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera Activa Mifos'),
        ),
        migrations.AddField(
            model_name='activewalletreport',
            name='resultMifosCa',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=core.models.upload_path, verbose_name='Cartera Activa Mifos'),
        ),
    ]
