SELECT 'Fecha_Proceso'
,'Id'
,'Estado'
,'Estado_Mambu'
,'Dias_Atraso'
,'Cuota_Capital'
,'Cuota_Interes'
,'Max_Atraso_Pago_Cuota'
,'Ultima_Fecha_Cobro'
,'Antiguedad_Cobro'
,'Plazo_Prestamo'
,'Fecha_Otorgado'
,'input_current_quota'
,'Tasa_Interes'
,'input_pending_capital'
,'input_original_capital'
,'Pais'
,'Nombre_Linea_Prestamo'
,'Id_Linea_Prestamo'
,'Sucursal_Prestamo'
,'Centro_Prestamo'
,'input_dni'
,'Cuil'
,'input_firstname'
,'input_lastname'
,'input_birthdate'
,'input_pending_quotas'
,'NroUltimaCuotaPaga'
,'Tipo_Fideicomiso'
,'Fideicomiso'
,'input_gender'
,'Es_Producto_Vigente'
,'input_brand'
,'Max_Score_BCRA'
,'Reglas_Bloqueo_Agente_Pago'
,'Tiene_Producto_Vigente'
,'Ids_Fideicomiso_Prestamo'
,'bucket_reno'
,'Score_Bhe'
,'Fecha_Score_Bhe'
,'Descs_Fideicomiso_Prestamo'
,'Segmento_Tasa'
,'input_remaining_installments'
,'input_last_lost_opportunity_date'
,'input_first_remaining_installment_date'
,'input_remaining_payment_cycle_business_day_ord'



UNION ALL
SELECT `Fecha_Proceso`
,`Id`
,`Estado`
,`Estado_Mambu`
,`Dias_Atraso`
,`Cuota_Capital`
,`Cuota_Interes`
,`Max_Atraso_Pago_Cuota`
,`Ultima_Fecha_Cobro`
,`Antiguedad_Cobro`
,`Plazo_Prestamo`
,`Fecha_Otorgado`
,`input_current_quota`
,`Tasa_Interes`
,`input_pending_capital`
,`input_original_capital`
,`Pais`
,`Nombre_Linea_Prestamo`
,`Id_Linea_Prestamo`
,`Sucursal_Prestamo`
,`Centro_Prestamo`
,`input_dni`
,`Cuil`
,`input_firstname`
,`input_lastname`
,`input_birthdate`
,`input_pending_quotas`
,`NroUltimaCuotaPaga`
,`Tipo_Fideicomiso`
,`Fideicomiso`
,`input_gender`
,`Es_Producto_Vigente`
,`input_brand`
,`Max_Score_BCRA`
,`Reglas_Bloqueo_Agente_Pago`
,`Tiene_Producto_Vigente`
,`Ids_Fideicomiso_Prestamo`
,`bucket_reno`
,`Score_Bhe`
,`Fecha_Score_Bhe`
,`Descs_Fideicomiso_Prestamo`
,`Segmento_Tasa`
,`input_remaining_installments`
,`input_last_lost_opportunity_date`
,`input_first_remaining_installment_date`
,`input_remaining_payment_cycle_business_day_ord`
FROM cartera_reno;