# Generated by Django 2.0.6 on 2018-07-26 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to='')),
                ('policy', models.CharField(max_length=50)),
                ('workflow', models.CharField(max_length=50)),
                ('result', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('score_access', 'Can access score'),),
                'verbose_name': 'Score',
                'verbose_name_plural': 'Score',
            },
        ),
    ]
